Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('',include('blogs.urls', namespace='blog')),
    path('register/', include('users.urls', namespace='users')),
]

Blog/blogs/urls.py
from django.urls import path
from .views import *


app_name = 'blog'
urlpatterns = [
    path('home/', HomeListView.as_view(), name='home'),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name='article'),
    path('add_post/', AddPostCreateView.as_view(), name= 'add_post'),
    path('edit_post/<int:pk>/', EditPostUpdateView.as_view(), name= 'edit_post'),
    path('delete_post/<int:pk>/', PostDeleteView.as_view(), name='delete_post'),
    path('category/<str:cate>/', CategoryView, name = 'category'),
]

Blog/users/urls.py
from django.urls import path
from .views import UserFormCreateView, LoginView, LogoutView, UserFormCreateView, AddCategoryViews


app_name = 'users'
urlpatterns = [
    path('', UserFormCreateView.as_view(), name = 'user_registration'),
    path('login/', LoginView.as_view(), name= 'login'),
    path('logout/', LogoutView.as_view(), name= 'logout'),
    path('registration/', UserFormCreateView.as_view(), name= 'registration'),
    path('addcategory/', AddCategoryViews, name= 'add_category'),
    
   


]

Blog/blogs/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse



class Category(models.Model):
    category = models.CharField(max_length=223, default= 'sport')
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.category


class Post(models.Model):
    """Model definition for Post."""

    # TODO: Define fields here
    title = models.CharField(max_length=225)
    author = models.ForeignKey(User, on_delete= models.CASCADE)
    body = models.TextField()
    category = models.CharField(max_length=255, default='sport')
    date_uploaded= models.DateTimeField(default= timezone.now)



    class Meta:
        """Meta definition for Post."""

        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        """Unicode representation of Post."""
        return self.title
        
    def get_absolute_url(self):     #this below snippet only work for a specific page with pk or id
        return reverse('blog:home',) #kwargs={'pk': self.pk})
    

Blog/users/models.py
from django.db import models

# Create your models here.

Blog/users/forms.py
from django import forms
from blogs.models import Category,Post


class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('category',)
        widgets ={
            'category': forms.TextInput(attrs={'class':'form-control', 'col':40})
        }
         
class EditCategory(forms.ModelForm):
    class Meta:
        model = Post
        fields =('category',)
        widgets = {
            'category': forms.TextInput(attrs={'class':'form-control', 'col':40})
        }

Blog/blogs/views.py
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .form_styles import PostForm
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm

#ListView = it list out all the records of a chosen model in database, and it usally called by a for loop
#DetailView = it bring out the details of one record of a chosen model in database instead of listing all like ListView
#CreateView = it create a new intance of an existing model in the database, and it's important to specify the field it should create, 
#if we are not using form class. it's through CreateView we handle form
class HomeListView(ListView):
    model = Post
    template_name = "home.html"
    ordering = '-date_uploaded'


class ArticleDetailView(DetailView):
    model = Post
    template_name = "article.html"

class AddPostCreateView(CreateView):
    model = Post
    template_name = "add_post.html"
    form_class = PostForm
    #specifying the field to create
    #fields = ['title','body']

class EditPostUpdateView(UpdateView):
    model = Post
    template_name = "edit_post.html"
    form_class = PostForm


class PostDeleteView(DeleteView):
    model = Post
    template_name = "delete_post.html"
    success_url = reverse_lazy('blog:home')

def CategoryView(request, cate):
    category = Post.objects.all().filter(category=cate)
    return render(request, 'category.html', {'cate':cate, 'posts_category': category})

Blog/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm 
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from users.forms import AddCategoryForm, EditCategory
from blogs.models import Category,Post


class UserFormCreateView(CreateView):
    form_class = UserCreationForm
    template_name = "users_authentication.html"
    success_url = reverse_lazy('users:login')

class LoginView(LoginView):
    template_name = 'login.html'
    
class LogoutView(LogoutView):
    template_name = 'logout.html'

def AddCategoryViews(request):
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            form.save() 
            return redirect('http://127.0.0.1:8000/home')
    else:
        form = AddCategoryForm()
    return render(request, 'add_category.html', {'form':form})

Blog/blogs/templates/add_post.html
{% extends 'base.html' %}

{% block title %}
Add New Post
{% endblock title %}


{% block content %}

{% if user.is_authenticated %}
<h1>Add Post</h1>
<br>
<div class="form-group">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Post</button>
    </form>
</div>
{% else %}
<h2>Page closed</h2>
<hr>
<p>Please <a href="{% url 'users:registration' %}">Sign Up</a> or <a href="{% url 'users:login' %}">Login</a></p>

    
{% endif %}
    
 
{% endblock content %}

Blog/blogs/templates/article.html
{% extends 'base.html' %}



{% block title %}
Blog article
{% endblock title %}


{% block content %}

{% if user.is_authenticated %}
    <h1>{{ post.title }}</h1><br>
    By {{post.author|title}}
    <hr>
    <!--tag "hr" draws a straight line across the browser-->
    <p>{{post.body}}</p>
    <a href="{% url 'blog:edit_post' post.pk %}">Edit</a>
    <br>
    <small>
        Posted on: {{post.date_uploaded}}
    </small>
    
    
    <br>
    
    <br>
    <a href=" {% url 'blog:home' %} " class="btn btn-primary">Back</a>
{% else %}
<h2>Page closed</h2>
<hr>
<p>Please <a href="{% url 'users:registration' %}">Sign Up</a> or <a href="{% url 'users:login' %}">Login</a></p>


{% endif %}
    

{% endblock content %}

Blog/blogs/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="./styles/index.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <title>

        {% block title %}

        {% endblock title %}

    </title>
</head>

<body style="background: coral;">
    <b> 
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">


                <a class="navbar-brand" href="#">Welcome</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'blog:home'%} ">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'blog:add_post'%} ">Add Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'users:add_category'%} ">Add Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'users:logout'%} ">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'users:login'%} ">Login</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'users:registration' %}">Sign Up</a>
                        </li>
                        {% endif %}






                </div>
            </div>
        </nav>
        <br>

        <div class="container">

            {% autoescape off %}
            {% block content %}

            {% endblock content %}
            {% endautoescape %}



        </div>

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0"
            crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
</body>

</html>

Blog/blogs/templates/category.html
{% extends 'base.html' %}


{% block content %}

{% if cate %}
    <h1>{{ cate|title }} Categories</h1>
    <br>
    {% for post in posts_category %}
    <li>
        <b>Post title:</b> {{post.title}}
        <br>
        <b>Author:</b> {{post.author|title}}
        <br>
        <small>Post: {{post.body|slice:":20"}}...</small>
        <br>
        <a href=" {% url 'blog:article' post.pk %} ">View full post</a><br>
        <a href=" {% url 'blog:delete_post' post.pk %} ">Delete post</a> <br>
        <hr>
    {% endfor %}
{% else %}
<h1>Sorry this page does not exist!!</h1>
{% endif %}
    
   
   
        
{% endblock content %}
    

Blog/blogs/templates/delete_post.html
{% extends 'base.html' %}


{% block title %}
Delete Post
{% endblock title %}


{% block content %}

{% if user.is_authenticated %}
    <h1>Delete Post</h1>
    <hr>
    <p>Are you sure you want to delete?</p>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-danger"> Yes</button>
        <a href="{% url 'blog:home' %} " class="btn btn-primary"> No</a>
    </form>
    {% else %}
    <h2>Page closed</h2>
    <hr>
    <p>Please <a href="{% url 'users:registration' %}">Sign Up</a> or <a href="{% url 'users:login' %}">Login</a></p>

{% endif %}
    

{% endblock content %}

Blog/blogs/templates/edit_post.html
{% extends 'base.html' %}

{% block title %}
Edit Post
{% endblock title %}


{% block content %}

{% if user.is_authenticated %}
    
<h1>Update Post</h1>
<br>
<div class="form-group">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Update</button>
    </form>
</div>
{% else %}
<h2>Page closed</h2>
<hr>
<p>Please <a href="{% url 'users:registration' %}">Sign Up</a> or <a href="{% url 'users:login' %}">Login</a></p>

{% endif %}

{% endblock content %}

Blog/blogs/templates/home.html
{% extends 'base.html' %}




{% block title %}
Block Home
{% endblock title %}



{% block content %}

{% if user.is_authenticated %}
    <h1>Posts</h1>
    <br>

    <!--Object list is all of the the queryset or blog post in database-->
    {% for post in object_list %}
    <li>
        <b>Post title:</b> {{post.title}}
        <br>
        <b>Author:</b> {{post.author|title}}
        <br>
        <small>Post: {{post.body|slice:":20"}}...</small>
        <br>
        <b>Category:</b> <a href="{% url 'blog:category' post.category|slugify %}">{{post.category|title}}</a> 
        <br>
        <a href=" {% url 'blog:article' post.pk %} ">View full post</a><br>
        <a href=" {% url 'blog:delete_post' post.pk %} ">Delete post</a> <br>
        <hr>

    </li>
{% endfor %}
    {% else %}
    <h2>Page closed</h2>
    <hr>
    <p>Please <a href="{% url 'users:registration' %}">Sign Up</a> or <a href="{% url 'users:login' %}">Login</a></p>

{% endif %}

{% endblock content %}

Blog/users/templates/add_category.html
{% extends 'base.html' %}

<h2>Add New Category</h2>

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary" type="submit">Post</button>
    </form>
{% endblock content %}
    

Blog/users/templates/login.html
{% extends 'base.html' %}

{% block title %}
User Login
{% endblock title %}


{% block content %}
<h1>User Login</h1>
<br>
<div class="form-group">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Login</button>
    </form>
</div>

{% endblock content %}

Blog/users/templates/logout.html
{% extends 'base.html' %}


{% block title %}
    Logout
{% endblock title %}


{% block content %}


    <h2>You've been logged out</h2>
    <hr>
    <p><a href="{% url 'users:login' %}">Login Again</a></p>
    
   
{% endblock content %}
    
    

Blog/users/templates/users_authentication.html
{% extends 'base.html' %}

{% block title %}
User Registration
{% endblock title %}


{% block content %}
<h1>User Registration</h1>
<br>
<div class="form-group">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary">Register</button>
    </form>
</div>

{% endblock content %}